### ISSUE TITLE
Improve documentation for submitting packages

### ISSUE THREAD

**Issue by scribblemaniac** [KaOSx/kaosx.github.io#20]
I was hoping to update an outdated KCP package for a project I help to develop. I have gone through https://kaosx.us/docs/package/ and https://kaosx.us/docs/kcp/ and haven't had any problems updating the PKGBUILD file, however submitting those changes has proved much more difficult. I tried [making a PR for it](https://github.com/KaOS-Community-Packages/pencil2d/pull/1). When that went nowhere I tried applying for membership in the section of the KCP Guide page. However that form does not appear to actually work (gave some error about the email address not being set up).

So I'd like to see that form fixed at least. Additionally, I'd like to see some documentation somewhere, either on the site or in the readme, for what the submission criteria and process is for packages in the main and apps repositories as it would be nice to move it to the official repository at some point.

**Comment by demmm** [comment]
>gave some error about the email address not being set up

To prevent spammers, a valid/legit email address is needed.  There were way too many spam mail/applications to not implement that.
So, question is, is there an issue with legit email addresses, or what was used? (and yes, the form is tested as working just fine with legit email addresses) .

>submission criteria and process is for packages in the main and apps repositories

Please read about KaOS and it's limited repos:
https://kaosx.us/about/
https://kaosx.us/about/faq/
Current amount of packages is what it will stay at (and has been the same level for the last 6 years).  When packages leave the repo, KCP packages that are popular are considered for replacements (stars). Users do not have final say, but there always is a thread in the forum were new options are discussed. (since your package was added 4 years ago, never maintained, not a single star, it is fairly safe to say, it is not/barely used, so not an option to be added).
https://forum.kaosx.us/d/2340-room-for-new-packages

**Comment by demmm** [comment]
No further response from submitter.closing.

**Comment by scribblemaniac** [comment]
Sorry for my lack of response. I was using a legitimate email address at the time, but perhaps the service was just having some temporary issues, or there was a conflict with my browser plugins or something like that. It appears to be working fine now.

Also thank you for the additional details. I did not find this clear in the linked documentation. It mentions the intent to limit the repositories multiple times, but it's rather vague as to *how* the repositories are limited (the numbers and criteria you mentioned for example). And none of that is found in the actual git repos, which is where I personally would first go to look for such details (either in a readme or contributing file).
